baseURL = "https://www.cilindir.ca/"
languageCode = "en-ca"
title = "Cilindir"
theme = "hugo-theme-lean-launch-page"
author = "Michael Luciuk"
canonifyurls = true
paginate = 3

googleAnalytics = ""

[params]
  tagline = "From Any Place to Every Face."

  images = [
    "cilindir-submark.svg",
    "cilindir-secondary-light.svg",
    "cilindir-favicon-light.svg",
    "cilindir-favicon-dark.svg"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true