baseURL = "https://www.cilindir.ca/"
languageCode = "en-ca"
title = "Cilindir"
theme = "hugo-theme-lean-launch-page"
author = "Michael Luciuk"
canonifyurls = true
paginate = 3

googleAnalytics = ""

[params]
  tagline = "From Any Place to Every Face."

  linkedin = "https://www.linkedin.com/company/cilindir/"
  github = "https://github.com/Cilindir/"

  images = ["cilindir.svg", "cilindir-submark.svg", "cilindir-favicon-light-mode.svg", "cilindir-favicon-dark-mode.svg"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true