baseURL = "https://www.cilindir.ca/"
languageCode = "en-ca"
title = "Cilindir"
theme = "hugo-theme-lean-launch-page"
author = "Michael Luciuk"
canonifyurls = true
paginate = 3

googleAnalytics = ""

[params]
  tagline = "From Any Place to Every Face."
  mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"

#  twitter = "https://twitter.com/MyNewProduct"
#  facebook = "https://facebook.com/MyNewProduct"
#  linkedin = "https://www.linkedin.com/company/MyNewProduct"
#  instagram = "https://instragram.com/MyNewProduct"
#  googleplus = "https://plus.google.com/+MyNewProduct"
  github = "https://github.com/Cilindir"

  images = ["favicon.png"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true